### ISSUE TITLE
bluetooth-hci-socket dependency not compatible with MacOS 10.12

### ISSUE THREAD

**Issue by ghost** [vheun/wedo2#2]
I get the following error when trying to install wedo2:

$ npm install wedo2 --save
npm WARN optional Skipping failed optional dependency /noble/bluetooth-hci-socket:
npm WARN notsup Not compatible with your operating system or architecture: bluetooth-hci-socket@0.5.1

I guess it has more to do with that module, but does that mean this module is Windows-only?

**Comment by vheun** [comment]
I believe the last update solved the problem. Can you check if it works?

**Comment by vheun** [comment]
This should definitely work now.
