### ISSUE TITLE
One motor not running, when two connected

### ISSUE THREAD

**Issue by dyachkovD** [vheun/wedo2#3]
I'm trying to get 2 motors to work together, but when running this code, only one motor is running
```javascript
wedo2.setMotor(100, 1, null); // first motor start running
wedo2.setMotor(100, 2, null); // nothing happens, first motor still running
```

**Comment by vheun** [comment]
Hi Dyachkov, I am finishing up my thesis right now. I will check this issue when I have some time. But in general, both motors should run. Can you try to put a delay between your calls?

**Comment by vheun** [comment]
Hi @dyachkovD this took a bit longer, but I believe I have found the issue.
With the latest version of Noble, I could not get any data in and out of the Wedo.
The bug is fixed with the latest version.
